api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-proxy

log:
  level: INFO

tls:
  certificates:
    - certFile: /etc/traefik/certs/localhost.cert
      keyFile: /etc/traefik/certs/localhost.key
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        - certFile: /etc/traefik/certs/localhost.cert
          keyFile: /etc/traefik/certs/localhost.key
