services:
  php:
    env_file: .env
    build: .
    working_dir: /var/www
    command: sh -c "composer install && php-fpm" # tail -f /dev/null
    volumes:
      - ./:/var/www
      - /var/www/vendor
    networks:
      - traefik-proxy

  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`${APP_HOST}`)"
      - "traefik.http.services.laravel.loadbalancer.server.port=80"

  vite:
    image: node:24-alpine
    working_dir: /var/www
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    ports:
      - "5173:5173"

networks:
  traefik-proxy:
    external: true
