services:
  nginx:
    image: node:24-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=Host(`node.localhost`)"
      - "traefik.http.services.node.loadbalancer.server.port=3000"

networks:
  traefik-proxy:
    external: true
